baseURL = 'https://joeybernard.github.io/'
languageCode = 'en-us'
title = 'The Rational Coder'
theme = ['risotto','ananke']

sectionPagesMenu = 'main'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
