[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[Params]
   author = "Joey Bernard"
   description = "Just a regular guy"
   paginate = 8

[[Params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/joeybernard"

[[Params.social]]
  icon = "linkedin"
  name = "My LinkedIn"
  url = "https://www.linkedin.com/in/joey-bernard-18b8791/"

[[Menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[Menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 2

[[Menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3
